apiVersion: "openstack.stable.sap.cc/v1"
kind: "OpenstackSeed"
metadata:
  name: nova-seed
spec:
  requires:
  - monsoon3/domain-default-seed
  - monsoon3/domain-ccadmin-seed
  - monsoon3/domain-monsoon3-seed

  roles:
  - compute_admin
  - compute_viewer
  - cloud_compute_admin
  - cloud_network_admin

  services:
  - name: nova
    type: compute
    description: Openstack Compute
 # uncomment once moved to helm-charts
 #    endpoints:
 #    - interface: admin
 #      region: {{ .Values.global.region }}
 #      url: https://{{include "nova_api_endpoint_host_public" .}}/v2/%(tenant_id)s
 #    - interface: internal
 #      region: {{ .Values.global.region }}
 #      url: http://nova-api.{{ .Release.Namespace }}.svc.kubernetes.{{ .Values.global.region }}.{{ .Values.global.tld }}:8774/v2/%(tenant_id)s
 #    - interface: public
 #      region: {{ .Values.global.region }}
 #      url: http://nova-api.{{ .Release.Namespace }}.svc.kubernetes.{{ .Values.global.region }}.{{ .Values.global.tld }}:8774/v2/%(tenant_id)s

  domains:
  - name: Default
    users:
    - name: admin
      roles:
      - domain: Default
        role: cloud_compute_admin
      - project: admin
        role: cloud_compute_admin
    - name: nova
      description: Nova Service
      #password: {{ .Values.global.nova_service_password }}
      roles:
      - project: service
        role: service
      - project: service
        role: admin
      - project: service
        role: cloud_network_admin
      - project: service
        role: cloud_compute_admin
    groups:
    - name: administrators
      roles:
      - domain: Default
        role: cloud_compute_admin
      - project: admin
        role: cloud_compute_admin

  - name: ccadmin
    projects:
    - name: cloud_admin
      roles:
      - user: admin@Default
        role: cloud_compute_admin
    groups:
    - name: CCADMIN_CLOUD_ADMINS
      roles:
      - project: cloud_admin
        role: cloud_compute_admin

  - name: monsoon3
    groups:
    - name: MONSOON3_DOMAIN_ADMINS
      roles:
      - project: cc-demo
        role: compute_admin
